In [2]:
print(torch.__version__)

2.2.0+cu118


In [1]:
import torch

In [3]:
torch.cuda.is_available()

True

In [4]:
import numpy as np
import os


In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
basic_tensor = torch.tensor([[1,2,3],[11,12,13]])
basic_tensor

tensor([[ 1,  2,  3],
        [11, 12, 13]])

In [7]:
basic_tensor.dtype

torch.int64

In [8]:
basic_tensor.device

device(type='cpu')

In [9]:
basic_tensor.shape

torch.Size([2, 3])

In [10]:
basic_tensor.requires_grad

False

In [11]:
# this are the thing are recquired while defining the tensors

tensor = torch.tensor([[1,2,3],[4,5,6]],
                      dtype = torch.float,
                      device = device,
                      requires_grad = True)
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [12]:
# checking the dtypes of tensor

tensor.dtype

torch.float32

In [13]:
# chcking the cuda available or not , if you have multiple gpu then you can setup multiple index in gpu
# currently it showing 0 beacuse we have only 1 gpu
tensor.device

device(type='cuda', index=0)

In [14]:
tensor.requires_grad

True

### Other commonly used tensors

In [16]:
y = torch.empty(size = (3,3))
y

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
x = torch.zeros(size = (3,3) )
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
z =torch.ones(size = (3,3))
z

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
w = torch.rand(size = (3,3))
w

tensor([[0.8483, 0.2405, 0.6553],
        [0.4406, 0.9412, 0.6305],
        [0.6417, 0.6402, 0.9192]])

### Identity matrix

In [21]:
x = torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### arange function

In [22]:

x = torch.arange(start = 0 ,  end = 7, step =1)
x

tensor([0, 1, 2, 3, 4, 5, 6])

### linspace

In [26]:
x = torch.linspace(start = 0, end = 10, steps = 7)
x

tensor([ 0.0000,  1.6667,  3.3333,  5.0000,  6.6667,  8.3333, 10.0000])

In [28]:
x = torch.rand(size = (3,4)).normal_(mean = 0, std = 1)
x

tensor([[-0.8973, -0.7854, -0.5053,  1.1749],
        [-1.1036,  0.5009,  0.0905,  0.4026],
        [-1.0403, -0.2097, -0.3234,  1.0991]])

In [29]:
x = torch.rand(size = (3,4)).uniform_(3,6)
x

tensor([[3.8755, 4.4498, 3.8582, 5.0901],
        [4.8197, 5.9696, 4.4703, 5.8097],
        [4.3614, 3.5882, 3.1257, 4.1806]])

In [30]:
x = torch.diag(torch.ones(10))
x

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
x.shape

torch.Size([10, 10])

In [32]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [34]:
x.int()

tensor([0, 1, 2, 3], dtype=torch.int32)

In [35]:
x.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [37]:
x.bool()

tensor([False,  True,  True,  True])

In [38]:
x.float()

tensor([0., 1., 2., 3.])

In [39]:
x.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [41]:
x  = np.array([[1,2,3],[1,2,3]])
x

array([[1, 2, 3],
       [1, 2, 3]])

In [43]:
torch_array = torch.from_numpy(x)
torch_array

tensor([[1, 2, 3],
        [1, 2, 3]], dtype=torch.int32)

In [44]:
torch_array.numpy()

array([[1, 2, 3],
       [1, 2, 3]])