In [1]:
import torch

In [2]:
print(torch.__version__)

2.2.0+cu118


In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [12]:
x = torch.arange(start = 10, end = 20, step = 4)
y = torch.arange(start = 20, end = 30, step = 4)

x.shape, y.shape

(torch.Size([3]), torch.Size([3]))

In [13]:
x + y

tensor([30, 38, 46])

In [6]:
x

tensor([10, 14, 18])

In [7]:
y

tensor([20, 24, 28])

In [8]:
x - y 

tensor([-10, -10, -10])

### element wise multiplication

In [9]:
x * y

tensor([200, 336, 504])

### element wise division

In [10]:
x / y

tensor([0.5000, 0.5833, 0.6429])

In [14]:
z = torch.ones(3)
z

tensor([1., 1., 1.])

In [16]:
z = z+x
z

tensor([11., 15., 19.])

In [19]:
# you can also add like this 
z.add_(x)

# basically you add the value of x = ([10, 14, 18])

tensor([41., 57., 73.])

In [20]:
# power
x.pow(2)

tensor([100, 196, 324])

In [21]:
# power
x**2

tensor([100, 196, 324])

In [22]:
x > 0 

tensor([True, True, True])

In [23]:
x < 0

tensor([False, False, False])

In [28]:
# Matrix Multiplication

a = torch.rand(size = (3,5))
b = torch.rand(size = (5,4))

a@b

tensor([[1.0010, 1.9967, 0.4976, 1.1570],
        [1.9210, 2.1102, 0.6484, 1.2557],
        [1.6242, 1.8023, 0.5721, 1.1775]])

In [29]:
# alternative of matrix multiplication

a.matmul(b)

tensor([[1.0010, 1.9967, 0.4976, 1.1570],
        [1.9210, 2.1102, 0.6484, 1.2557],
        [1.6242, 1.8023, 0.5721, 1.1775]])

In [30]:
x = torch.rand((3,3))
x.matrix_exp()

tensor([[2.1191, 1.0681, 0.8166],
        [1.4708, 3.2776, 2.5367],
        [0.9982, 2.0772, 3.0325]])

In [31]:
x.matrix_power(2)

tensor([[0.5970, 0.6625, 0.6157],
        [0.9300, 1.5510, 1.5276],
        [0.7295, 1.2583, 1.3458]])

In [32]:
# element wise multiplication
x * y

tensor([[11.8236,  9.4981,  4.7732],
        [10.4712, 17.6563, 27.8743],
        [ 4.7280, 19.3476, 19.8569]])

In [40]:
# dot product - dot prduct work on 1d tensor not on 2d and 3d tensors
torch.dot(x,y)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [46]:
x = torch.arange(start =10, end =20, step = 7)
y = torch.arange(start = 30, end = 40, step = 7)

In [47]:
y

tensor([30, 37])

In [48]:
x

tensor([10, 17])

In [49]:
torch.dot(x, y)

tensor(929)